plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('run/server')
        }
    }
}

repositories {
    maven { url = "https://maven.terraformersmc.com/releases/" } // Trinkets
    maven { url = "https://maven.ladysnake.org/releases" } // CCA (for Trinkets)
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    modImplementation("curse.maven:immersive-paintings-639584:${immersive_paintings_fabric_file}")

    modImplementation("me.fzzyhmstrs:fzzy_config:${fzzy_config_version}")
    modImplementation("com.terraformersmc:modmenu:${modmenu_version}")

    // Trinkets and CCA
    modImplementation("dev.emi:trinkets:${trinkets_fabric_version}")
//    modCompileOnly("dev.emi:trinkets:${trinkets_fabric_version}") { exclude(group: "com.terraformersmc") }
//    modCompileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${cca_fabric_version}")
//    modCompileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${cca_fabric_version}")

    // WebP library for Immersive Paintings, not needed for compile time
    runtimeOnly("com.twelvemonkeys.common:common-lang:${webp_version}")
    runtimeOnly("com.twelvemonkeys.common:common-image:${webp_version}")
    runtimeOnly("com.twelvemonkeys.imageio:imageio-core:${webp_version}")
    runtimeOnly("com.twelvemonkeys.imageio:imageio-webp:${webp_version}")

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}
