org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.22)
enabled_platforms=fabric,neoforge
java_version=21

mod_id=betsyross
mod_name=Betsy Ross
mod_author=rbasamoyai
mod_version=3.1.0
group=com.rbasamoyai
credits=
license=MIT
description=Large flags with images across the internets
mod_sources=https://github.com/Wagers-of-Industrial-Warfare/BetsyRoss
mod_issues=https://github.com/Wagers-of-Industrial-Warfare/BetsyRoss/issues

#qm_version=23
parchment_version=2024.11.17

fabric_loader_version=0.16.10
fabric_api_version=0.115.4+1.21.1

neoforge_version=21.1.219
neoforge_loader_version_range=[4,)

#forge_version=1.20.1-47.1.43

mixinextras_version=0.5.0

# Dependencies
#immersive_paintings_forge_file = 4789114
immersive_paintings_neoforge_file = 7019925
immersive_paintings_fabric_file = 7019924
# works both neoforge and fabric
fzzy_config_version=0.7.0+1.21
#config_api_id = 4583000
#night_config_version = 3.6.3
webp_version=3.12.0

# Integration
#curios_forge_version = 5.9.1+1.20.1
curios_neoforge_version = 9.5.1+1.21.1
trinkets_fabric_version = 3.10.0

# Sable integration
sable_version = 1.2.1

# QoL
modmenu_version=11.0.3

# requirements (versioning)
immersive_paintings_neoforge_requirement = 0.7.4
immersive_paintings_fabric_requirement = 0.7.4
fzzy_config_neoforge_requirement = 0.7.0
fzzy_config_fabric_requirement = 0.7.0
curios_requirement = 9.2.0
trinkets_requirement = 3.10.0
sable_requirement = 1.2.0
