org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.22)
enabled_platforms=fabric,neoforge
java_version=21

mod_id=betsyross
mod_name=Betsy Ross
mod_author=rbasamoyai
mod_version=3.0.0
group=com.rbasamoyai
credits=
license=MIT
mod_sources=https://github.com/Wagers-of-Industrial-Warfare/BetsyRoss
mod_issues=https://github.com/Wagers-of-Industrial-Warfare/BetsyRoss/issues

#qm_version=23
parchment_version=2024.11.17

fabric_loader_version=0.16.10
fabric_api_version=0.115.4+1.21.1

neoforge_version=21.1.154
neoforge_loader_version_range=[4,)

#forge_version=1.20.1-47.1.43

mixinextras_version=0.5.0

# Dependencies
#immersive_paintings_forge_file = 4789114
immersive_paintings_neoforge_file = 4789114
immersive_paintings_fabric_file = 7019924
fzzy_config_version=0.7.0+1.21
#config_api_id = 4583000
#night_config_version = 3.6.3

# Integration
curios_forge_version = 5.9.1+1.20.1
trinkets_fabric_version = 3.10.0
cca_fabric_version = 5.2.1

# QoL
modmenu_version=11.0.3

# requirements (versioning)
immersive_paintings_neoforge_requirement = 0.7.4
immersive_paintings_fabric_requirement = 0.7.4
curios_requirement = 5.9.1
trinkets_requirement = 3.10.0
