plugins {
    id 'multiloader-common'
    id 'fabric-loom'
}

repositories {
//    maven {
//        name = "Fuzs Mod Resources"
//        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
//    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
    }

    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}")

    modImplementation("me.fzzyhmstrs:fzzy_config:${fzzy_config_version}")
    modImplementation("curse.maven:immersive-paintings-639584:${immersive_paintings_fabric_file}")

    //api("dev.ryanhcode.sable:sable-common-${minecraft_version}:${sable_version}") // Sable

    annotationProcessor(implementation("io.github.llamalad7:mixinextras-common:${mixinextras_version}")) // MixinExtras

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
}
